channels:
- conda-forge
dependencies:
- python=3.12.3
- pip<=24.2
- pip:
  - mlflow==2.17.2
  - cloudpickle==3.1.0
  - lz4==4.3.3
  - numpy==2.0.0
  - pandas==2.2.2
  - psutil==6.1.0
  - scikit-learn==1.5.2
  - scipy==1.14.1
name: mlflow-env
